@startuml Sequence Diagram 

actor User as U
participant "Application Controller" as AC
participant "ODE Solver" as ODES

participant "Input Page" as IP
participant "Graph Page" as GP
participant "Phase Page" as PP
participant "Table Page" as TP
participant "Tester Page" as TP


AC -> IP: Open Page
IP -> IP: Generate Self
U -> IP: Input Data
IP -> AC: Send Input
AC -> ODES: Solve ODE
ODES --> AC: Return Solution
AC -> GP: Generate with Solution Object
GP -> GP: Generate Self
AC -> PP: Generate with Solution Object
PP -> PP: Generate Self
AC -> TP: Generate with Solution Object
TP -> TP: Generate Self
@enduml